<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>

		<!-- ✅ Version app -->
		<Version>0.9.8</Version>
		<AssemblyVersion>0.9.8.0</AssemblyVersion>
		<FileVersion>0.9.8.0</FileVersion>

		<ApplicationIcon>PommeBrowser_desktop.ico</ApplicationIcon>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="Assets\logo.png" />
		<None Remove="Assets\PommeBrowser_desktop.ico" />
		<None Remove="Assets\PommeBrowser_geek.png" />
		<None Remove="Assets\ssl_bad.png" />
		<None Remove="Assets\ssl_ok.png" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="PommeBrowser_desktop.ico" />
	</ItemGroup>

	<ItemGroup>
		<Resource Include="Assets\logo.png" />
		<Resource Include="Assets\PommeBrowser_desktop.ico" />
		<Resource Include="Assets\PommeBrowser_geek.png" />
		<Resource Include="Assets\ssl_bad.png" />
		<Resource Include="Assets\ssl_ok.png" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.9" />
		<PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4078.44" />
		<PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" Version="3.53.3" />
		<PackageReference Include="Velopack" Version="1.2.0" />
	</ItemGroup>


	<ItemGroup>
		<Content Include="Assets\Ruffle\**\*" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
	</ItemGroup>
</Project>