<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>

		<!-- ✅ Version app -->
		<Version>0.8.0</Version>
		<AssemblyVersion>0.8.0.0</AssemblyVersion>
		<FileVersion>0.8.0.0</FileVersion>

		<ApplicationIcon>PommeBrowser_desktop.ico</ApplicationIcon>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="Assets\logo.png" />
		<None Remove="Assets\PommeBrowser_desktop.ico" />
		<None Remove="Assets\ssl_bad.png" />
		<None Remove="Assets\ssl_ok.png" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="PommeBrowser_desktop.ico" />
	</ItemGroup>

	<ItemGroup>
		<Resource Include="Assets\logo.png" />
		<Resource Include="Assets\PommeBrowser_desktop.ico" />
		<Resource Include="Assets\ssl_bad.png" />
		<Resource Include="Assets\ssl_ok.png" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.1" />
		<PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3650.58" />
		<PackageReference Include="Velopack" Version="0.0.1298" />
	</ItemGroup>

</Project>